name: CI

on:
  push:
    branches:
      - "**"

jobs:

  test:
    permissions:
      contents: 'read'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Build
        run: |
          make build-docker

      - name: Test
        run: |
          make test-docker
